version: '1.0.0'
services:
  web:
    build: .
    ports:
      - 8080:8080
    links:
      - "mysql:mysql.local"
    volumes:
      - ./data/wordpress/:/home/site/
  mysql:
    image: mysql:8.2
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=wp
    volumes:
      - ./data/mysql:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_HOST=mysql
